from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name='home_guest'),
    path('login/', views.login_page, name='login_page'),
    path('manager_login/', views.manager_login, name='manager_login'),
    path('register/', views.register_page, name='Register'),
    path('profile/', views.profile, name='Profile'),
    path('user-home/', views.home2, name='home_user'),
    path('about_guest/', views.about_guest, name='About_guest'),
    path('about_user/', views.about_user, name='About_user'),
    path('logout/', views.logout, name='logout'),
    path('search/', views.search_pets, name='search_pets'),
    path('search/results/', views.search_results, name='search_results'),
    path('manager_dashboard/', views.manager_dashboard, name='manager_dashboard'),
    # path('request_adoption/', views.request_adoption, name='request_adoption'),
    path('test/',views.test,name='test'),
    path('adoption_request/<int:request_id>/', views.approve_decline_adoption, name='approve_decline_adoption'),
    path('manager/employees/', views.view_all_employees, name='view_all_employees'),
    path('manager/pets/', views.view_all_available_pets, name='view_all_available_pets'),
    path('manager/adoption-requests/', views.view_all_adoption_requests, name='view_all_adoption_requests'),
    path('register_pet/<int:request_id>/', views.register_pet_and_health_status, name='register_pet_and_health_status'),
    path('crud_employee/', views.crud_operations_employee, name='crud_operations_employee'),
    path('crud_available_pet/', views.crud_operations_available_pet, name='crud_operations_available_pet'),
   path('employees/create/', views.create_employee, name='create_employee'),
    path('select_employee/', views.select_employee_to_update, name='select_employee'),
    path('update_employee/<int:employee_id>/', views.update_employee, name='update_employee'),
    path('employees/delete/', views.delete_employee, name='delete_employee'),
    path('pets/create/',  views.create_available_pet, name='create_available_pet'),
    path('select-available-pet/', views.select_available_pet_to_update, name='select_available_pet'),
    path('update-available-pet/<int:pet_id>/', views.update_available_pet, name='update_available_pet'),
    path('load-data/', views.load_data_view),
    path('pets/delete/',  views.delete_available_pet, name='delete_available_pet'),
    path('appointment/',views.appointment,name='appointment'),
    path('register_pet_page/',views.register_pet_page,name='register_pet_page'),
    path('supplies/',views.supplies,name='supplies'),
     path('book_appointment/', views.book_appointment, name='book_appointment'),
     path('owned_pets/',views.owned_pets,name='owned_pets'),
    path('health-status/<int:pet_id>/', views.view_health_status, name='view_health_status'),
    path('contacts/', views.view_contacts, name='view_contacts'),
    path('download_health_status/<int:pet_id>/', views.download_health_status, name='download_health_status'),
    path('order/',views.ordered,name='ordered'),
]
