# Generated by Django 5.1.1 on 2024-10-31 06:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=10)),
                ('contact_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')])),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.DecimalField(decimal_places=0, max_digits=3, primary_key=True, serialize=False)),
                ('contact_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')])),
                ('man_pw', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OwnedPet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=20)),
                ('species', models.CharField(max_length=15)),
                ('breed', models.CharField(max_length=20)),
                ('adoption_source', models.CharField(choices=[('shop', 'Shop'), ('external', 'External')], max_length=8)),
                ('adoption_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('pw', models.CharField(max_length=30)),
                ('owner_name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(blank=True, max_length=30, null=True)),
                ('phone_no', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('city', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PetSupply',
            fields=[
                ('supply_id', models.AutoField(primary_key=True, serialize=False)),
                ('supply_type', models.CharField(choices=[('food', 'Food'), ('toys', 'Toys'), ('grooming', 'Grooming'), ('healthcare', 'Healthcare'), ('accessories', 'Accessories')], max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier_info', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailablePet',
            fields=[
                ('av_id', models.AutoField(primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=15)),
                ('breed', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_adoption_and_care.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=30)),
                ('salary', models.PositiveIntegerField()),
                ('contact_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')])),
                ('job_role', models.CharField(max_length=15)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_adoption_and_care.manager')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_adoption_and_care.manager'),
        ),
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('allergies', models.CharField(blank=True, max_length=50, null=True)),
                ('medications', models.CharField(blank=True, max_length=100, null=True)),
                ('last_checkup_date', models.DateField(blank=True, null=True)),
                ('next_checkup_date', models.DateField(blank=True, null=True)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pet_adoption_and_care.ownedpet')),
            ],
        ),
        migrations.AddField(
            model_name='ownedpet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_adoption_and_care.owner'),
        ),
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('reqstatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], max_length=8)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_adoption_and_care.availablepet')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_adoption_and_care.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('Medical Care', 'Medical Care'), ('Adoption', 'Adoption'), ('Supplies', 'Supplies')], max_length=15)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('review_date', models.DateField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_adoption_and_care.owner')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_placed', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_adoption_and_care.owner')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_adoption_and_care.petsupply')),
            ],
        ),
    ]
