# Generated by Django 5.1.1 on 2024-11-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_adoption_and_care', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email_id',
            field=models.EmailField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_no',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, unique=True),
        ),
    ]
