# Generated by Django 5.1.1 on 2024-11-01 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_adoption_and_care', '0002_alter_owner_email_id_alter_owner_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='manager',
            new_name='manager_id',
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='pet_adoption_and_care.manager'),
        ),
    ]
