# Generated by Django 5.1.1 on 2024-11-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_adoption_and_care', '0003_rename_manager_employee_manager_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
