# Generated by Django 5.1.1 on 2024-11-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_adoption_and_care', '0004_manager_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='reqstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=8),
        ),
    ]
