# Generated by Django 5.1.1 on 2024-11-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_adoption_and_care', '0005_alter_adoptionrequest_reqstatus'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adoptionrequest',
            unique_together={('owner', 'pet')},
        ),
    ]
