# Generated by Django 5.1.1 on 2024-11-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_adoption_and_care', '0007_availablepet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
